env: "local" # local, dev, prod
database:
  host: localhost
  port: 5432
  user: tyrandel
  dbname: orders
  sslmode: disable
http_server:
  address: "localhost:8080"
  timeout: 4s # время на чтение запроса / отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом
